FROM node:22
WORKDIR /home/node/app
RUN npm config set registry https://registry.npmmirror.com
RUN npm i pnpm -g
RUN npm i next -g
COPY . /home/node/app
RUN pnpm i
RUN pnpm run build
CMD ["npm", "start"]